name: Profile Picture Release

on:
  push:
    branches:
      - main
    paths:
      - 'profile-pictures/**'
      - '.github/workflows/profile-picture-release.yml'

jobs:
  create-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      - name: Install Inkscape
        run: sudo apt install -y inkscape
      - name: Create Images
        run: |
          cd ./profile-pictures
          ./convert.sh
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          name: 'Profile Pictures'
          tag: 'profile-pictures-${{ env.date }}'
          artifacts: 'profile-pictures/*.png'
          draft: true
